/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {Treatment} from './treatment';
import {Staff} from './staff';
import {AppointmentStatus} from './appointment-status';
import {Client} from './client';
import {Location} from './location';


export interface Appointment {
  duration?: any;
  endTime?: string;
  startTime?: string;
  appointmentStatus?: AppointmentStatus;
  client?: Client;
  createdDate?: string;
  date?: any;
  id?: number;
  lastModifiedBy?: string;
  lastModifiedDate?: string;
  location?: Location;
  notes?: string;
  staff?: Staff;
  treatment?: Treatment;
  price?: number
}

