/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Address } from './address';
import { ReferralSource } from './referral-source';
import { Person } from './person';


export interface Client { 
    address?: Address;
    birthday?: string;
    createdDate?: string;
    gender?: string;
    id?: number;
    language?: string;
    lastModifiedBy?: string;
    lastModifiedDate?: string;
    marketingNotifications?: boolean;
    notes?: string;
    notificationMethod?: string;
    person?: Person;
    referralSource?: ReferralSource;
}

